// lib/export/excel.ts — Excel (XLSX) exports via SheetJS
import * as XLSX from 'xlsx';
import type { Employee, PayrollRun, PayrollLineItem, Company } from '@/types';
import { formatDate } from '@/lib/utils';

type Row = (string | number)[];

function aoaSheet(rows: Row[], colWidths?: number[]): XLSX.WorkSheet {
  const ws = XLSX.utils.aoa_to_sheet(rows);
  if (colWidths) ws['!cols'] = colWidths.map((w) => ({ wch: w }));
  return ws;
}

function downloadBook(sheets: { name: string; ws: XLSX.WorkSheet }[], filename: string): void {
  const wb = XLSX.utils.book_new();
  for (const s of sheets) XLSX.utils.book_append_sheet(wb, s.ws, s.name.slice(0, 31));
  XLSX.writeFile(wb, filename);
}

const r2 = (n: number) => Math.round((n + Number.EPSILON) * 100) / 100;

/* ------------------------------------------- IRC Monthly SWT Remittance */

export function exportIRCMonthly(
  runs: PayrollRun[],
  monthLabel: string,
  company: Company,
): void {
  // Aggregate SWT per employee across all runs in the month.
  const byEmp = new Map<string, { name: string; num: string; dept: string; gross: number; swt: number }>();
  for (const run of runs) {
    for (const li of run.lineItems) {
      const cur = byEmp.get(li.employeeId) ?? {
        name: li.employeeName,
        num: li.employeeNumber,
        dept: li.department,
        gross: 0,
        swt: 0,
      };
      cur.gross += li.taxableIncome;
      cur.swt += li.swtDeduction;
      byEmp.set(li.employeeId, cur);
    }
  }

  const rows: Row[] = [];
  rows.push(['IRC SALARY & WAGES TAX — MONTHLY REMITTANCE']);
  rows.push([company.name]);
  rows.push([`TIN: ${company.tinnNumber ?? '—'}`, '', `IPA: ${company.ipaNumber ?? '—'}`]);
  rows.push([`Period: ${monthLabel}`]);
  rows.push([]);
  rows.push(['Employee #', 'Employee Name', 'Department', 'Taxable Income (K)', 'SWT Withheld (K)']);

  let totalGross = 0;
  let totalSWT = 0;
  for (const e of byEmp.values()) {
    rows.push([e.num, e.name, e.dept, r2(e.gross), r2(e.swt)]);
    totalGross += e.gross;
    totalSWT += e.swt;
  }
  rows.push([]);
  rows.push(['', '', 'TOTALS', r2(totalGross), r2(totalSWT)]);
  rows.push([]);
  rows.push(['Total SWT payable to IRC:', '', '', '', r2(totalSWT)]);
  rows.push([`Generated by PNG Payroll Pro — ${formatDate(new Date())}`]);

  downloadBook(
    [{ name: 'SWT Remittance', ws: aoaSheet(rows, [14, 26, 18, 18, 18]) }],
    `IRC_SWT_Remittance_${monthLabel.replace(/\s+/g, '_')}.xlsx`,
  );
}

/* ------------------------------------------- Annual Group Tax Certificate */

export function exportGroupTaxCert(
  year: string,
  runs: PayrollRun[],
  company: Company,
): void {
  const byEmp = new Map<
    string,
    { name: string; num: string; gross: number; swt: number; eeSuper: number; erSuper: number }
  >();
  for (const run of runs) {
    for (const li of run.lineItems) {
      const cur = byEmp.get(li.employeeId) ?? {
        name: li.employeeName,
        num: li.employeeNumber,
        gross: 0,
        swt: 0,
        eeSuper: 0,
        erSuper: 0,
      };
      cur.gross += li.totalEarnings;
      cur.swt += li.swtDeduction;
      cur.eeSuper += li.employeeSuperDeduction;
      cur.erSuper += li.employerSuperContribution;
      byEmp.set(li.employeeId, cur);
    }
  }

  const rows: Row[] = [];
  rows.push([`GROUP TAX CERTIFICATE (IRC Form 12 equivalent) — ${year}`]);
  rows.push([company.name, '', `TIN: ${company.tinnNumber ?? '—'}`]);
  rows.push([]);
  rows.push([
    'Employee #',
    'Employee Name',
    'Annual Gross (K)',
    'Total SWT Withheld (K)',
    'Employee Super (K)',
    'Employer Super (K)',
  ]);
  for (const e of byEmp.values()) {
    rows.push([e.num, e.name, r2(e.gross), r2(e.swt), r2(e.eeSuper), r2(e.erSuper)]);
  }

  downloadBook(
    [{ name: `Group Tax ${year}`, ws: aoaSheet(rows, [14, 26, 18, 20, 18, 18]) }],
    `Group_Tax_Certificate_${year}.xlsx`,
  );
}

/* ------------------------------------------- Payroll Ledger / Audit */

export function exportLedger(items: Array<PayrollLineItem & { runNumber: string; payDate: string }>): void {
  const rows: Row[] = [
    [
      'Run #',
      'Pay Date',
      'Employee #',
      'Employee',
      'Department',
      'Gross (K)',
      'Allowances (K)',
      'Taxable (K)',
      'SWT (K)',
      'EE Super (K)',
      'Net Pay (K)',
      'ER Super (K)',
      'Cost (K)',
      'Tax Bracket',
    ],
  ];
  for (const i of items) {
    rows.push([
      i.runNumber,
      formatDate(i.payDate),
      i.employeeNumber,
      i.employeeName,
      i.department,
      r2(i.grossSalary),
      r2(i.totalAllowances),
      r2(i.taxableIncome),
      r2(i.swtDeduction),
      r2(i.employeeSuperDeduction),
      r2(i.netPay),
      r2(i.employerSuperContribution),
      r2(i.totalCostToCompany),
      i.taxBracket,
    ]);
  }
  downloadBook(
    [{ name: 'Payroll Ledger', ws: aoaSheet(rows, [12, 12, 12, 22, 16, 12, 14, 12, 12, 12, 12, 12, 12, 14]) }],
    `Payroll_Ledger_${new Date().toISOString().slice(0, 10)}.xlsx`,
  );
}

/* ------------------------------------------- Department cost */

export function exportDepartmentCost(rows: Array<{ dept: string; employees: number; gross: number; cost: number }>): void {
  const data: Row[] = [['Department', 'Employees', 'Gross (K)', 'Total Cost (K)']];
  let g = 0;
  let c = 0;
  for (const r of rows) {
    data.push([r.dept, r.employees, r2(r.gross), r2(r.cost)]);
    g += r.gross;
    c += r.cost;
  }
  data.push(['TOTAL', rows.reduce((a, r) => a + r.employees, 0), r2(g), r2(c)]);
  downloadBook(
    [{ name: 'Department Cost', ws: aoaSheet(data, [22, 12, 16, 16]) }],
    `Department_Cost_${new Date().toISOString().slice(0, 10)}.xlsx`,
  );
}

/* ------------------------------------------- Employee list */

export function exportEmployeesXLSX(employees: Employee[]): void {
  const rows: Row[] = [
    ['Employee #', 'First Name', 'Last Name', 'Department', 'Position', 'Type', 'Fortnightly Salary (K)', 'Nasfund', 'Status', 'Phone', 'Email'],
  ];
  for (const e of employees) {
    rows.push([
      e.employeeNumber,
      e.firstName,
      e.lastName,
      e.department,
      e.position,
      e.employmentType,
      r2(e.grossFortnightlySalary),
      e.nasfundMember ? 'Yes' : 'No',
      e.status,
      e.phone,
      e.email ?? '',
    ]);
  }
  downloadBook(
    [{ name: 'Employees', ws: aoaSheet(rows, [12, 14, 14, 16, 18, 12, 18, 10, 12, 16, 26]) }],
    `Employees_${new Date().toISOString().slice(0, 10)}.xlsx`,
  );
}
